project_id = "tickrx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["tickrx://", "http://localhost:8081"]

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
